repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        files: README.md

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        types: [java]
        language: system
        files: \.java$

      - id: unittest
        name: unittest
        entry: make test
        types: [java]
        language: system
        files: \.java$
